pygments: true
permalink: pretty
markdown: redcarpet
redcarpet: 
  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
title: "webscale"
author:
  name: "saml"
  github: "saml"
description: "webscale"
urls:
  base: "http://i.webscale.info"
  cdn: ""
